  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      run: apache-php
    name: apache-php
  spec:
    replicas: 2
    selector:
      matchLabels:
        run: apache-php
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: apache-php
      spec:
        containers:
        - image: kodka/php-apache:latest
          name: apache-php
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
