apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-storage
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/data"
